### ISSUE TITLE
Clean up autogenerated files

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/xmodalg#1]
You can clean up https://github.com/gap-packages/xmodalg/tree/master/doc directory
- it's recommended to not to keep under version control files that are generated
automatically. What you need to keep there is only *.xml.

**Comment by aodabas** [comment]
autogenerated files have been cleaned.

**Comment by olexandr-konovalov** [comment]
@aodabas great! By the way, you could write `Closes #1` somewhere (e.g. in the 3rd line of commit message in this case) and this issue would be closed automatically.
