### ISSUE TITLE
Diffs in tests with GAP 4.9.1 release candidates

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/xmodalg#13]
There are currently some diffs in the package tests when they are run with the `stable-4.9` branch of the GAP repository. Please see https://travis-ci.org/gap-system/gap-docker-pkg-tests-stable-4.9-staging to inspect them: click on the line corresponding to this package and scroll till the very end of the log file to see the output of the package tests, the summary, and further instructions.

As soon as the package tests will run without diffs, they will be moved to https://travis-ci.org/gap-system/gap-docker-pkg-tests-stable-4.9. This will be very helpful to monitor in the future that the package is still usable and that no changes in the GAP system break the package.

**Comment by aodabas** [comment]
I am confused. I cloned the stable-4.9 in my virtual ubuntu. Then the package tests has run without diffs. 

I checked the end of the log file in https://travis-ci.org/gap-system/gap-docker-pkg-tests-stable-4.9-staging. The variables "f1" and "f2" appear to have been replaced in somewhere.

**Comment by olexandr-konovalov** [comment]
Tests also pass in https://travis-ci.org/gap-packages/xmodalg. Some random algorithms are involved, or the set of loaded packages. One could try to compile all packages in Travis, instead of selected ones, and then see if the problem will be observable in Travis too. Then adjust tests to the current output. A better strategy would be however to rework examples to make them less dependent on randomness.

**Comment by cdwensley** [comment]
It seems to be that this issue can now be closed.  The Travis diffs were due, not to any random method, but to the Semigroups package producing different sets of algebra generators.  The test files have been adjusted to avoid printing these list of generators and the tests now pass on Travis.  New issue #18 is a reminder that the test changes might eventually be reverted.

**Comment by aodabas** [comment]
thank you
