### ISSUE TITLE
Printing of algebra generators in tests. 

### ISSUE THREAD

**Issue by cdwensley** [gap-packages/xmodalg#18]
The Travis tests were producing diffs because Semigroups fails to build. 
xmod.tst and cat1.tst no longer print the problematic lists of algebra generators 
(though the original GAP commands and output remain in the manual). 
One day, when Semigroups does compile on Travis, these changes can be reverted.

**Comment by olexandr-konovalov** [comment]
Actually, it builds in one of the three configurations, with clang: https://travis-ci.org/gap-packages/xmodalg/builds/357451573?utm_source=github_status&utm_medium=notification

**Comment by cdwensley** [comment]
Well I've added io and profiling but it appears that Semigroups 3.0.14 fails to build. 
Probably not worth pressing on with this?

**Comment by olexandr-konovalov** [comment]
I suggest to add building io, profiling and semigroups and temporary rely on the testing done with clang.

**Comment by cdwensley** [comment]
If we did that, and the PR was merged, what would appear on https://travis-ci.org/gap-packages/ - 
a tick or a cross?  It just happens that the latest Semigroups PR produces an entry there with a tick. 
This is all very puzzling!

**Comment by olexandr-konovalov** [comment]
They use slightly different Travis setup. We may have to look at that.

**Comment by cdwensley** [comment]
Tests now changed to avoid printing of algebra generators. 
Semigroups is irrelevant - it was a SuggestedOtherPackage in groupoids, but no longer.
