### ISSUE TITLE
Clean up tests

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/xmodalg#2]
You may see test logs e.g. at https://travis-ci.org/gap-system/gap-docker-pkg-tests-stable/jobs/281452101

Currently the test passes with default set of packages loaded, but fails otherwise. It will be useful to investigate that, check if there any errors (e.g. when GAP is started with no packages, some calculations return `fail` instead of a meaningful result???), and make tests more reproducible.

**Comment by cdwensley** [comment]
Having updated the manual I will next work on the tests - if that's OK?
